version: '3.3'
services:
  redis:
    platform: linux/x86_64
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - currencyconverterredisdb:/data
volumes:
  currencyconverterredisdb: