export interface Currency {
  numCode: number;
  code: string;
  name: string;
  enabled: boolean;
}

export class CurrencyService {
  private readonly baseCurrencyCode = 'UAH';
  private readonly currencies: Currency[] = [
    {
      numCode: 784,
      code: 'AED',
      name: 'United Arab Emirates Dirham',
      enabled: true,
    },
    {
      numCode: 971,
      code: 'AFN',
      name: 'Afghan Afghani',
      enabled: true,
    },
    {
      numCode: 8,
      code: 'ALL',
      name: 'Albanian Lek',
      enabled: true,
    },
    {
      numCode: 51,
      code: 'AMD',
      name: 'Armenian Dram',
      enabled: true,
    },
    {
      numCode: 532,
      code: 'ANG',
      name: 'Netherlands Antillean Guilder',
      enabled: false,
    },
    {
      numCode: 973,
      code: 'AOA',
      name: 'Angolan Kwanza',
      enabled: true,
    },
    {
      numCode: 32,
      code: 'ARS',
      name: 'Argentine Peso',
      enabled: true,
    },
    {
      numCode: 36,
      code: 'AUD',
      name: 'Australian Dollar',
      enabled: true,
    },
    {
      numCode: 533,
      code: 'AWG',
      name: 'Aruban Florin',
      enabled: false,
    },
    {
      numCode: 944,
      code: 'AZN',
      name: 'Azerbaijani Manat',
      enabled: true,
    },
    {
      numCode: 977,
      code: 'BAM',
      name: 'Bosnia and Herzegovina Convertible Mark',
      enabled: false,
    },
    {
      numCode: 52,
      code: 'BBD',
      name: 'Barbadian Dollar',
      enabled: false,
    },
    {
      numCode: 50,
      code: 'BDT',
      name: 'Bangladeshi Taka',
      enabled: true,
    },
    {
      numCode: 975,
      code: 'BGN',
      name: 'Bulgarian Lev',
      enabled: true,
    },
    {
      numCode: 48,
      code: 'BHD',
      name: 'Bahraini Dinar',
      enabled: true,
    },
    {
      numCode: 108,
      code: 'BIF',
      name: 'Burundian Franc',
      enabled: true,
    },
    {
      numCode: 60,
      code: 'BMD',
      name: 'Bermudian Dollar',
      enabled: false,
    },
    {
      numCode: 96,
      code: 'BND',
      name: 'Brunei Dollar',
      enabled: true,
    },
    {
      numCode: 68,
      code: 'BOB',
      name: 'Bolivian Boliviano',
      enabled: true,
    },
    {
      numCode: 986,
      code: 'BRL',
      name: 'Brazilian Real',
      enabled: true,
    },
    {
      numCode: 44,
      code: 'BSD',
      name: 'Bahamian Dollar',
      enabled: false,
    },
    {
      numCode: 64,
      code: 'BTN',
      name: 'Bhutanese Ngultrum',
      enabled: false,
    },
    {
      numCode: 72,
      code: 'BWP',
      name: 'Botswana Pula',
      enabled: true,
    },
    {
      numCode: 933,
      code: 'BYN',
      name: 'Belarusian Ruble',
      enabled: true,
    },
    {
      numCode: 84,
      code: 'BZD',
      name: 'Belize Dollar',
      enabled: false,
    },
    {
      numCode: 124,
      code: 'CAD',
      name: 'Canadian Dollar',
      enabled: true,
    },
    {
      numCode: 976,
      code: 'CDF',
      name: 'Congolese Franc',
      enabled: true,
    },
    {
      numCode: 756,
      code: 'CHF',
      name: 'Swiss Franc',
      enabled: true,
    },
    {
      numCode: null,
      code: 'CKD',
      name: 'Cook Islands Dollar',
      enabled: false,
    },
    {
      numCode: 152,
      code: 'CLP',
      name: 'Chilean Peso',
      enabled: true,
    },
    {
      numCode: 156,
      code: 'CNY',
      name: 'Chinese Yuan',
      enabled: true,
    },
    {
      numCode: 170,
      code: 'COP',
      name: 'Colombian Peso',
      enabled: true,
    },
    {
      numCode: 188,
      code: 'CRC',
      name: 'Costa Rican Colon',
      enabled: true,
    },
    {
      numCode: 931,
      code: 'CUC',
      name: 'Cuban convertible Peso',
      enabled: false,
    },
    {
      numCode: 192,
      code: 'CUP',
      name: 'Cuban Peso',
      enabled: true,
    },
    {
      numCode: 132,
      code: 'CVE',
      name: 'Cabo Verdean Escudo',
      enabled: false,
    },
    {
      numCode: 203,
      code: 'CZK',
      name: 'Czech Koruna',
      enabled: true,
    },
    {
      numCode: 262,
      code: 'DJF',
      name: 'Djiboutian Franc',
      enabled: true,
    },
    {
      numCode: 208,
      code: 'DKK',
      name: 'Danish Krone',
      enabled: true,
    },
    {
      numCode: 214,
      code: 'DOP',
      name: 'Dominican Peso',
      enabled: false,
    },
    {
      numCode: 12,
      code: 'DZD',
      name: 'Algerian Dinar',
      enabled: true,
    },
    {
      numCode: 818,
      code: 'EGP',
      name: 'Egyptian Pound',
      enabled: true,
    },
    {
      numCode: null,
      code: 'EHP',
      name: 'Sahrawi Peseta',
      enabled: false,
    },
    {
      numCode: 232,
      code: 'ERN',
      name: 'Eritrean Nakfa',
      enabled: false,
    },
    {
      numCode: 230,
      code: 'ETB',
      name: 'Ethiopian Birr',
      enabled: true,
    },
    {
      numCode: 978,
      code: 'EUR',
      name: 'Euro',
      enabled: true,
    },
    {
      numCode: 242,
      code: 'FJD',
      name: 'Fijian Dollar',
      enabled: false,
    },
    {
      numCode: 238,
      code: 'FKP',
      name: 'Falkland Islands Pound',
      enabled: false,
    },
    {
      numCode: null,
      code: 'FOK',
      name: 'Faroese Króna',
      enabled: false,
    },
    {
      numCode: 826,
      code: 'GBP',
      name: 'Pound Sterling',
      enabled: true,
    },
    {
      numCode: 981,
      code: 'GEL',
      name: 'Georgian Lari',
      enabled: true,
    },
    {
      numCode: null,
      code: 'GGP',
      name: 'Guernsey Pound',
      enabled: false,
    },
    {
      numCode: 936,
      code: 'GHS',
      name: 'Ghanaian Cedi',
      enabled: true,
    },
    {
      numCode: 292,
      code: 'GIP',
      name: 'Gibraltar Pound',
      enabled: false,
    },
    {
      numCode: 270,
      code: 'GMD',
      name: 'Gambian Dalasi',
      enabled: true,
    },
    {
      numCode: 324,
      code: 'GNF',
      name: 'Guinean Franc',
      enabled: true,
    },
    {
      numCode: 320,
      code: 'GTQ',
      name: 'Guatemalan Quetzal',
      enabled: false,
    },
    {
      numCode: 328,
      code: 'GYD',
      name: 'Guyanese Dollar',
      enabled: false,
    },
    {
      numCode: 344,
      code: 'HKD',
      name: 'Hong Kong Dollar',
      enabled: true,
    },
    {
      numCode: 340,
      code: 'HNL',
      name: 'Honduran Lempira',
      enabled: false,
    },
    {
      numCode: 191,
      code: 'HRK',
      name: 'Croatian Kuna',
      enabled: true,
    },
    {
      numCode: 332,
      code: 'HTG',
      name: 'Haitian Gourde',
      enabled: false,
    },
    {
      numCode: 348,
      code: 'HUF',
      name: 'Hungarian Forint',
      enabled: true,
    },
    {
      numCode: 360,
      code: 'IDR',
      name: 'Indonesian Rupiah',
      enabled: true,
    },
    {
      numCode: 376,
      code: 'ILS',
      name: 'Israeli new Shekel',
      enabled: true,
    },
    {
      numCode: null,
      code: 'IMP',
      name: 'Manx Pound',
      enabled: false,
    },
    {
      numCode: 356,
      code: 'INR',
      name: 'Indian Rupee',
      enabled: true,
    },
    {
      numCode: 368,
      code: 'IQD',
      name: 'Iraqi Dinar',
      enabled: true,
    },
    {
      numCode: 364,
      code: 'IRR',
      name: 'Iranian Rial',
      enabled: false,
    },
    {
      numCode: 352,
      code: 'ISK',
      name: 'Icelandic Krona',
      enabled: true,
    },
    {
      numCode: null,
      code: 'JEP',
      name: 'Jersey Pound',
      enabled: false,
    },
    {
      numCode: 388,
      code: 'JMD',
      name: 'Jamaican Dollar',
      enabled: false,
    },
    {
      numCode: 400,
      code: 'JOD',
      name: 'Jordanian Dinar',
      enabled: true,
    },
    {
      numCode: 392,
      code: 'JPY',
      name: 'Japanese Yen',
      enabled: true,
    },
    {
      numCode: 404,
      code: 'KES',
      name: 'Kenyan Shilling',
      enabled: true,
    },
    {
      numCode: 417,
      code: 'KGS',
      name: 'Kyrgyzstani Som',
      enabled: true,
    },
    {
      numCode: 116,
      code: 'KHR',
      name: 'Cambodian Riel',
      enabled: true,
    },
    {
      numCode: null,
      code: 'KID',
      name: 'Kiribati Dollar',
      enabled: false,
    },
    {
      numCode: 174,
      code: 'KMF',
      name: 'Comorian Franc',
      enabled: false,
    },
    {
      numCode: 408,
      code: 'KPW',
      name: 'North Korean Won',
      enabled: false,
    },
    {
      numCode: 410,
      code: 'KRW',
      name: 'South Korean Won',
      enabled: true,
    },
    {
      numCode: 414,
      code: 'KWD',
      name: 'Kuwaiti Dinar',
      enabled: true,
    },
    {
      numCode: 136,
      code: 'KYD',
      name: 'Cayman Islands Dollar',
      enabled: false,
    },
    {
      numCode: 398,
      code: 'KZT',
      name: 'Kazakhstani Tenge',
      enabled: true,
    },
    {
      numCode: 418,
      code: 'LAK',
      name: 'Lao Kip',
      enabled: true,
    },
    {
      numCode: 422,
      code: 'LBP',
      name: 'Lebanese Pound',
      enabled: true,
    },
    {
      numCode: 144,
      code: 'LKR',
      name: 'Sri Lankan Rupee',
      enabled: true,
    },
    {
      numCode: 430,
      code: 'LRD',
      name: 'Liberian Dollar',
      enabled: false,
    },
    {
      numCode: 426,
      code: 'LSL',
      name: 'Lesotho Loti',
      enabled: false,
    },
    {
      numCode: 434,
      code: 'LYD',
      name: 'Libyan Dinar',
      enabled: true,
    },
    {
      numCode: 504,
      code: 'MAD',
      name: 'Moroccan Dirham',
      enabled: true,
    },
    {
      numCode: 498,
      code: 'MDL',
      name: 'Moldovan Leu',
      enabled: true,
    },
    {
      numCode: 969,
      code: 'MGA',
      name: 'Malagasy Ariary',
      enabled: true,
    },
    {
      numCode: 807,
      code: 'MKD',
      name: 'Macedonian Denar',
      enabled: true,
    },
    {
      numCode: 104,
      code: 'MMK',
      name: 'Myanmar Kyat',
      enabled: false,
    },
    {
      numCode: 496,
      code: 'MNT',
      name: 'Mongolian Tögrög',
      enabled: true,
    },
    {
      numCode: 446,
      code: 'MOP',
      name: 'Macanese Pataca',
      enabled: false,
    },
    {
      numCode: 929,
      code: 'MRU',
      name: 'Mauritanian Ouguiya',
      enabled: false,
    },
    {
      numCode: 480,
      code: 'MUR',
      name: 'Mauritian Rupee',
      enabled: true,
    },
    {
      numCode: 462,
      code: 'MVR',
      name: 'Maldivian Rufiyaa',
      enabled: false,
    },
    {
      numCode: 454,
      code: 'MWK',
      name: 'Malawian Kwacha',
      enabled: true,
    },
    {
      numCode: 484,
      code: 'MXN',
      name: 'Mexican Peso',
      enabled: true,
    },
    {
      numCode: 458,
      code: 'MYR',
      name: 'Malaysian Ringgit',
      enabled: true,
    },
    {
      numCode: 943,
      code: 'MZN',
      name: 'Mozambican Metical',
      enabled: true,
    },
    {
      numCode: 516,
      code: 'NAD',
      name: 'Namibian Dollar',
      enabled: true,
    },
    {
      numCode: 566,
      code: 'NGN',
      name: 'Nigerian Naira',
      enabled: true,
    },
    {
      numCode: 558,
      code: 'NIO',
      name: 'Nicaraguan Córdoba',
      enabled: true,
    },
    {
      numCode: 578,
      code: 'NOK',
      name: 'Norwegian Krone',
      enabled: true,
    },
    {
      numCode: 524,
      code: 'NPR',
      name: 'Nepalese Rupee',
      enabled: true,
    },
    {
      numCode: 554,
      code: 'NZD',
      name: 'New Zealand Dollar',
      enabled: true,
    },
    {
      numCode: 512,
      code: 'OMR',
      name: 'Omani Rial',
      enabled: true,
    },
    {
      numCode: 590,
      code: 'PAB',
      name: 'Panamanian Balboa',
      enabled: false,
    },
    {
      numCode: 604,
      code: 'PEN',
      name: 'Peruvian Sol',
      enabled: true,
    },
    {
      numCode: 598,
      code: 'PGK',
      name: 'Papua New Guinean Kina',
      enabled: false,
    },
    {
      numCode: 608,
      code: 'PHP',
      name: 'Philippine Peso',
      enabled: true,
    },
    {
      numCode: 586,
      code: 'PKR',
      name: 'Pakistani Rupee',
      enabled: true,
    },
    {
      numCode: 985,
      code: 'PLN',
      name: 'Polish Zloty',
      enabled: true,
    },
    {
      numCode: null,
      code: 'PND',
      name: 'Pitcairn Islands Dollar',
      enabled: false,
    },
    {
      numCode: null,
      code: 'PRB',
      name: 'Transnistrian Ruble',
      enabled: false,
    },
    {
      numCode: 600,
      code: 'PYG',
      name: 'Paraguayan Guaraní',
      enabled: true,
    },
    {
      numCode: 634,
      code: 'QAR',
      name: 'Qatari Riyal',
      enabled: true,
    },
    {
      numCode: 946,
      code: 'RON',
      name: 'Romanian Leu',
      enabled: true,
    },
    {
      numCode: 941,
      code: 'RSD',
      name: 'Serbian Dinar',
      enabled: true,
    },
    {
      numCode: 643,
      code: 'RUB',
      name: 'Russian Ruble',
      enabled: false,
    },
    {
      numCode: 646,
      code: 'RWF',
      name: 'Rwandan Franc',
      enabled: false,
    },
    {
      numCode: 682,
      code: 'SAR',
      name: 'Saudi Riyal',
      enabled: true,
    },
    {
      numCode: 90,
      code: 'SBD',
      name: 'Solomon Islands Dollar',
      enabled: false,
    },
    {
      numCode: 690,
      code: 'SCR',
      name: 'Seychellois Rupee',
      enabled: true,
    },
    {
      numCode: 938,
      code: 'SDG',
      name: 'Sudanese Pound',
      enabled: true,
    },
    {
      numCode: 752,
      code: 'SEK',
      name: 'Swedish Krona',
      enabled: true,
    },
    {
      numCode: 702,
      code: 'SGD',
      name: 'Singapore Dollar',
      enabled: true,
    },
    {
      numCode: 654,
      code: 'SHP',
      name: 'Saint Helena Pound',
      enabled: false,
    },
    {
      numCode: 694,
      code: 'SLL',
      name: 'Sierra Leonean Leone',
      enabled: true,
    },
    {
      numCode: null,
      code: 'SLS',
      name: 'Somaliland Shilling',
      enabled: false,
    },
    {
      numCode: 706,
      code: 'SOS',
      name: 'Somali Shilling',
      enabled: true,
    },
    {
      numCode: 968,
      code: 'SRD',
      name: 'Surinamese Dollar',
      enabled: true,
    },
    {
      numCode: 728,
      code: 'SSP',
      name: 'South Sudanese Pound',
      enabled: false,
    },
    {
      numCode: 930,
      code: 'STN',
      name: 'Sao Tome and Príncipe Dobra',
      enabled: false,
    },
    {
      numCode: 222,
      code: 'SVC',
      name: 'Salvadoran Colón',
      enabled: false,
    },
    {
      numCode: 760,
      code: 'SYP',
      name: 'Syrian Pound',
      enabled: false,
    },
    {
      numCode: 748,
      code: 'SZL',
      name: 'Swazi Lilangeni',
      enabled: true,
    },
    {
      numCode: 764,
      code: 'THB',
      name: 'Thai Baht',
      enabled: true,
    },
    {
      numCode: 972,
      code: 'TJS',
      name: 'Tajikistani Somoni',
      enabled: true,
    },
    {
      numCode: 934,
      code: 'TMT',
      name: 'Turkmenistan Manat',
      enabled: false,
    },
    {
      numCode: 788,
      code: 'TND',
      name: 'Tunisian Dinar',
      enabled: true,
    },
    {
      numCode: 776,
      code: 'TOP',
      name: 'Tongan Paʻanga',
      enabled: false,
    },
    {
      numCode: 949,
      code: 'TRY',
      name: 'Turkish Lira',
      enabled: true,
    },
    {
      numCode: 780,
      code: 'TTD',
      name: 'Trinidad and Tobago Dollar',
      enabled: false,
    },
    {
      numCode: null,
      code: 'TVD',
      name: 'Tuvaluan Dollar',
      enabled: false,
    },
    {
      numCode: 901,
      code: 'TWD',
      name: 'New Taiwan Dollar',
      enabled: true,
    },
    {
      numCode: 834,
      code: 'TZS',
      name: 'Tanzanian Shilling',
      enabled: true,
    },
    {
      numCode: 980,
      code: 'UAH',
      name: 'Ukrainian Hryvnia',
      enabled: true,
    },
    {
      numCode: 800,
      code: 'UGX',
      name: 'Ugandan Shilling',
      enabled: true,
    },
    {
      numCode: 840,
      code: 'USD',
      name: 'United States Dollar',
      enabled: true,
    },
    {
      numCode: 858,
      code: 'UYU',
      name: 'Uruguayan Peso',
      enabled: true,
    },
    {
      numCode: 860,
      code: 'UZS',
      name: 'Uzbekistani Som',
      enabled: true,
    },
    {
      numCode: null,
      code: 'VED',
      name: 'Venezuelan bolívar digital',
      enabled: false,
    },
    {
      numCode: 928,
      code: 'VES',
      name: 'Venezuelan Bolívar Soberano',
      enabled: false,
    },
    {
      numCode: 704,
      code: 'VND',
      name: 'Vietnamese Dong',
      enabled: true,
    },
    {
      numCode: 548,
      code: 'VUV',
      name: 'Vanuatu Vatu',
      enabled: false,
    },
    {
      numCode: 882,
      code: 'WST',
      name: 'Samoan Tala',
      enabled: false,
    },
    {
      numCode: 950,
      code: 'XAF',
      name: 'Central African CFA Franc BEAC',
      enabled: true,
    },
    {
      numCode: 951,
      code: 'XCD',
      name: 'East Caribbean Dollar',
      enabled: false,
    },
    {
      numCode: 952,
      code: 'XOF',
      name: 'West African CFA Franc BCEAO',
      enabled: true,
    },
    {
      numCode: 953,
      code: 'XPF',
      name: 'CFP Franc (Franc Pacifique)',
      enabled: false,
    },
    {
      numCode: 886,
      code: 'YER',
      name: 'Yemeni Rial',
      enabled: true,
    },
    {
      numCode: 710,
      code: 'ZAR',
      name: 'South African Rand',
      enabled: true,
    },
    {
      numCode: 967,
      code: 'ZMW',
      name: 'Zambian Kwacha',
      enabled: false,
    },
    {
      numCode: null,
      code: 'ZWB',
      name: 'RTGS Dollar',
      enabled: false,
    },
    {
      numCode: 932,
      code: 'ZWL',
      name: 'Zimbabwean Dollar',
      enabled: false,
    },
    {
      numCode: null,
      code: 'Abkhazia',
      name: 'Abkhazian Apsar',
      enabled: false,
    },
    {
      numCode: null,
      code: 'Artsakh',
      name: 'Artsakh Dram',
      enabled: false,
    },
  ];

  list(): Currency[] {
    return this.currencies.filter((currency) => currency.enabled);
  }

  getCurrencyByCode(code: string): Currency {
    return this.currencies.find(
      (currency) => currency.code === code && currency.enabled,
    );
  }

  getCurrencyByNumCode(numCode: number): Currency {
    return this.currencies.find(
      (currency) => currency.numCode === numCode && currency.enabled,
    );
  }
  isBaseCurrency(currency: Currency): boolean {
    return currency.code === this.baseCurrencyCode;
  }
  getBaseCurrency(): Currency {
    return this.getCurrencyByCode(this.baseCurrencyCode);
  }
}
